// next-env.d.ts is generated by `next dev|build` and gitignored; referencing
// Next's ambient types here keeps `tsc --noEmit` working on a fresh clone
// (CSS modules, image imports, JSX intrinsic extensions).
/// <reference types="next" />
/// <reference types="next/image-types/global" />
